/**
 * Vitrin / kategori testi için örnek ilanlar.
 * Admin panelinden yüklenir; ornek: true ile işaretlenir.
 */

const ORNEK_KONUM = {
  latitude: 41.015137,
  longitude: 28.97953,
  il: 'İstanbul',
  ilce: 'Kadıköy',
  etiket: 'Kadıköy, İstanbul',
};

export const ORNEK_ILANLAR = [
  {
    baslik: 'Satılık 3+1 Daire — Kadıköy',
    aciklama: 'Metroya yakın, aydınlık, masrafsız daire. Örnek vitrin ilanıdır.',
    fiyat: '4500000',
    kategori: 'Emlak',
    kategoriId: 'daire',
    kategoriKok: 'emlak',
    kategoriYolu: ['emlak', 'konut', 'satilik', 'daire'],
    kategoriEtiket: 'Emlak › Konut › Satılık › Daire',
    platformlar: ['Sahibinden', 'Emlakjet'],
    konum: ORNEK_KONUM,
    detay: { emlakTipi: 'Daire', ilanTuru: 'Satılık', metrekare: '120', odaSayisi: '3+1', binaYasi: '8' },
  },
  {
    baslik: 'Satılık Rezidans — Beşiktaş',
    aciklama: 'Güvenlikli site, havuz ve spor salonu. Örnek ilan.',
    fiyat: '12500000',
    kategori: 'Emlak',
    kategoriId: 'rezidans',
    kategoriKok: 'emlak',
    kategoriYolu: ['emlak', 'konut', 'satilik', 'rezidans'],
    kategoriEtiket: 'Emlak › Konut › Satılık › Rezidans',
    platformlar: ['Sahibinden', 'Emlakjet'],
    konum: { ...ORNEK_KONUM, ilce: 'Beşiktaş', etiket: 'Beşiktaş, İstanbul' },
    detay: { emlakTipi: 'Rezidans', ilanTuru: 'Satılık', metrekare: '185', odaSayisi: '4+1' },
  },
  {
    baslik: 'Kiralık 2+1 Daire — Üsküdar',
    aciklama: 'Eşyalı, aidat dahil değil. Örnek kiralık ilan.',
    fiyat: '28000',
    kategori: 'Emlak',
    kategoriId: 'kiralik-daire',
    kategoriKok: 'emlak',
    kategoriYolu: ['emlak', 'konut', 'kiralik', 'kiralik-daire'],
    kategoriEtiket: 'Emlak › Konut › Kiralık › Daire',
    platformlar: ['Sahibinden'],
    konum: { ...ORNEK_KONUM, ilce: 'Üsküdar', etiket: 'Üsküdar, İstanbul' },
    detay: { emlakTipi: 'Daire', ilanTuru: 'Kiralık', metrekare: '95', odaSayisi: '2+1' },
  },
  {
    baslik: 'Satılık Villa — Bodrum',
    aciklama: 'Deniz manzaralı müstakil villa. Örnek ilan.',
    fiyat: '28500000',
    kategori: 'Emlak',
    kategoriId: 'villa',
    kategoriKok: 'emlak',
    kategoriYolu: ['emlak', 'konut', 'satilik', 'villa'],
    kategoriEtiket: 'Emlak › Konut › Satılık › Villa',
    platformlar: ['Sahibinden', 'Emlakjet'],
    konum: { latitude: 37.0344, longitude: 27.4305, il: 'Muğla', ilce: 'Bodrum', etiket: 'Bodrum' },
    detay: { emlakTipi: 'Villa', ilanTuru: 'Satılık', metrekare: '320', odaSayisi: '5+2' },
  },
  {
    baslik: 'Satılık Arsa — Çankaya',
    aciklama: 'İmarlı konut arsası. Örnek arsa ilanı.',
    fiyat: '8500000',
    kategori: 'Emlak',
    kategoriId: 'arsa',
    kategoriKok: 'emlak',
    kategoriYolu: ['emlak', 'arsa'],
    kategoriEtiket: 'Emlak › Arsa',
    platformlar: ['Sahibinden'],
    konum: { latitude: 39.9208, longitude: 32.8541, il: 'Ankara', ilce: 'Çankaya', etiket: 'Çankaya, Ankara' },
    detay: { emlakTipi: 'Arsa', ilanTuru: 'Satılık', metrekare: '450', imarDurumu: 'Konut' },
  },
  {
    baslik: '2020 Toyota Corolla 1.6 Vision',
    aciklama: 'Hatasız, bakımlı, tek elden. Örnek vasıta ilanı.',
    fiyat: '985000',
    kategori: 'Araç',
    kategoriId: 'otomobil',
    kategoriKok: 'vasita',
    kategoriYolu: ['vasita', 'otomobil'],
    kategoriEtiket: 'Vasıta › Otomobil',
    platformlar: ['Sahibinden', 'Arabam.com'],
    konum: ORNEK_KONUM,
    detay: { aracTipi: 'otomobil', marka: 'Toyota', model: 'Corolla', yil: '2020', kilometre: '62000', yakit: 'Benzin', vites: 'Otomatik' },
  },
  {
    baslik: 'Peugeot Partner Panelvan 2021',
    aciklama: 'Minivan & panelvan örnek ilanı.',
    fiyat: '650000',
    kategori: 'Araç',
    kategoriId: 'minivan',
    kategoriKok: 'vasita',
    kategoriYolu: ['vasita', 'minivan'],
    kategoriEtiket: 'Vasıta › Minivan & Panelvan',
    platformlar: ['Sahibinden', 'Arabam.com'],
    konum: ORNEK_KONUM,
    detay: { marka: 'Peugeot', model: 'Partner', yil: '2021', kilometre: '140000', yakit: 'Dizel' },
  },
  {
    baslik: 'iPhone 14 Pro Max 256 GB',
    aciklama: 'Kutusunda, garantili. Örnek ikinci el ilanı.',
    fiyat: '42000',
    kategori: 'İkinci El',
    kategoriId: 'cep-telefonu',
    kategoriKok: 'ikinci-el',
    kategoriYolu: ['ikinci-el', 'cep-telefonu'],
    kategoriEtiket: 'İkinci El ve Sıfır Alışveriş › Cep Telefonu',
    platformlar: ['Sahibinden', 'Letgo'],
    konum: ORNEK_KONUM,
    detay: { urunTipi: 'Cep Telefonu', marka: 'Apple', durum: 'İyi' },
  },
  {
    baslik: 'MacBook Air M2 — Sıfır Ayarında',
    aciklama: 'Az kullanılmış laptop. Örnek ilan.',
    fiyat: '38500',
    kategori: 'İkinci El',
    kategoriId: 'bilgisayar',
    kategoriKok: 'ikinci-el',
    kategoriYolu: ['ikinci-el', 'bilgisayar'],
    kategoriEtiket: 'İkinci El ve Sıfır Alışveriş › Bilgisayar',
    platformlar: ['Sahibinden'],
    konum: ORNEK_KONUM,
    detay: { urunTipi: 'Laptop', marka: 'Apple', durum: 'Sıfır Ayarında' },
  },
  {
    baslik: '2019 John Deere Traktör',
    aciklama: 'İş makinesi örnek ilanı.',
    fiyat: '1250000',
    kategori: 'İş Makineleri',
    kategoriId: 'traktor-john-deere',
    kategoriKok: 'is-makineleri',
    kategoriYolu: ['is-makineleri', 'is-makineleri-grup', 'satilik', 'traktor', 'traktor-john-deere'],
    kategoriEtiket: 'İş Makineleri & Sanayi › İş Makineleri › Satılık › Traktör › John Deere',
    platformlar: ['Sahibinden'],
    konum: { latitude: 39.9334, longitude: 32.8597, il: 'Ankara', ilce: 'Polatlı', etiket: 'Polatlı, Ankara' },
    detay: { marka: 'John Deere', model: '5M', yil: '2019', calismaSaati: '2500' },
  },
];
