/**
 * Vitrin / kategori testi için örnek ilanlar (Sahibinden tarzı demo).
 * Admin panelinden yüklenir; ornek: true ile işaretlenir.
 */

import { ornekIlanFotograflar, ORNEK_ESKI_BASLIKLAR } from './ornekIlanFotolari';

export { ornekIlanFotograflar, ORNEK_ESKI_BASLIKLAR };

const ORNEK_KONUM = {
  latitude: 41.015137,
  longitude: 28.97953,
  il: 'İstanbul',
  ilce: 'Kadıköy',
  etiket: 'Kadıköy, İstanbul',
};

const ORNEK_ILANLAR_HAM = [
  {
    ornekKey: 'ornek-emlak-daire-kadikoy',
    baslik: 'Satılık 3+1 Daire — Kadıköy',
    aciklama:
      'Moda\'ya yürüme mesafesinde, güney cephe, doğalgazlı kombi. Site içi otopark ve güvenlik mevcut. Tapu müsait, krediye uygun.',
    fiyat: '4500000',
    kategori: 'Emlak',
    kategoriId: 'daire',
    kategoriKok: 'emlak',
    kategoriYolu: ['emlak', 'konut', 'satilik', 'daire'],
    kategoriEtiket: 'Emlak › Konut › Satılık › Daire',
    platformlar: ['Sahibinden', 'Emlakjet'],
    konum: ORNEK_KONUM,
    detay: { emlakTipi: 'Daire', ilanTuru: 'Satılık', metrekare: '120', odaSayisi: '3+1', binaYasi: '8' },
  },
  {
    ornekKey: 'ornek-emlak-rezidans-besiktas',
    baslik: 'Satılık Rezidans — Beşiktaş',
    aciklama:
      '7/24 güvenlik, kapalı otopark, fitness ve havuz. Boğaz manzaralı salon, ankastre mutfak, yerden ısıtma.',
    fiyat: '12500000',
    kategori: 'Emlak',
    kategoriId: 'rezidans',
    kategoriKok: 'emlak',
    kategoriYolu: ['emlak', 'konut', 'satilik', 'rezidans'],
    kategoriEtiket: 'Emlak › Konut › Satılık › Rezidans',
    platformlar: ['Sahibinden', 'Emlakjet'],
    konum: { ...ORNEK_KONUM, ilce: 'Beşiktaş', etiket: 'Beşiktaş, İstanbul' },
    detay: { emlakTipi: 'Rezidans', ilanTuru: 'Satılık', metrekare: '185', odaSayisi: '4+1' },
  },
  {
    ornekKey: 'ornek-emlak-kiralik-uskudar',
    baslik: 'Kiralık 2+1 Daire — Üsküdar',
    aciklama:
      'Metrobus durağına 3 dk, eşyalı, balkonlu. Aidat 1.200 TL, depozito 2 kira. Hemen taşınmaya uygun.',
    fiyat: '28000',
    kategori: 'Emlak',
    kategoriId: 'kiralik-daire',
    kategoriKok: 'emlak',
    kategoriYolu: ['emlak', 'konut', 'kiralik', 'kiralik-daire'],
    kategoriEtiket: 'Emlak › Konut › Kiralık › Daire',
    platformlar: ['Sahibinden'],
    konum: { ...ORNEK_KONUM, ilce: 'Üsküdar', etiket: 'Üsküdar, İstanbul' },
    detay: { emlakTipi: 'Daire', ilanTuru: 'Kiralık', metrekare: '95', odaSayisi: '2+1', esyali: 'Evet' },
  },
  {
    ornekKey: 'ornek-emlak-villa-bodrum',
    baslik: 'Satılık Villa — Bodrum',
    aciklama:
      'Özel havuzlu, 4 oda 3 banyo, deniz manzaralı bahçe. Yaz-kış yaşamaya uygun, jeneratör ve güneş paneli mevcut.',
    fiyat: '28500000',
    kategori: 'Emlak',
    kategoriId: 'villa',
    kategoriKok: 'emlak',
    kategoriYolu: ['emlak', 'konut', 'satilik', 'villa'],
    kategoriEtiket: 'Emlak › Konut › Satılık › Villa',
    platformlar: ['Sahibinden', 'Emlakjet'],
    konum: { latitude: 37.0344, longitude: 27.4305, il: 'Muğla', ilce: 'Bodrum', etiket: 'Bodrum' },
    detay: { emlakTipi: 'Villa', ilanTuru: 'Satılık', metrekare: '320', odaSayisi: '5+2' },
  },
  {
    ornekKey: 'ornek-emlak-daire-izmir',
    baslik: 'Satılık 2+1 Daire — Bornova',
    aciklama:
      'Ege Üniversitesi yakını, asansörlü bina, doğalgazlı. Balkonlu, aydınlık salon, otopark mevcut.',
    fiyat: '3200000',
    kategori: 'Emlak',
    kategoriId: 'daire',
    kategoriKok: 'emlak',
    kategoriYolu: ['emlak', 'konut', 'satilik', 'daire'],
    kategoriEtiket: 'Emlak › Konut › Satılık › Daire',
    platformlar: ['Sahibinden', 'Emlakjet'],
    konum: { latitude: 38.4237, longitude: 27.1428, il: 'İzmir', ilce: 'Bornova', etiket: 'Bornova, İzmir' },
    detay: { emlakTipi: 'Daire', ilanTuru: 'Satılık', metrekare: '95', odaSayisi: '2+1', binaYasi: '5' },
  },
  {
    ornekKey: 'ornek-emlak-daire-antalya',
    baslik: 'Satılık 3+1 Daire — Kepez',
    aciklama: 'Denize 10 dk, site içi havuz ve güvenlik. Geniş mutfak, ebeveyn banyosu, kapalı otopark.',
    fiyat: '2750000',
    kategori: 'Emlak',
    kategoriId: 'daire',
    kategoriKok: 'emlak',
    kategoriYolu: ['emlak', 'konut', 'satilik', 'daire'],
    kategoriEtiket: 'Emlak › Konut › Satılık › Daire',
    platformlar: ['Sahibinden'],
    konum: { latitude: 36.8969, longitude: 30.7133, il: 'Antalya', ilce: 'Kepez', etiket: 'Kepez, Antalya' },
    detay: { emlakTipi: 'Daire', ilanTuru: 'Satılık', metrekare: '130', odaSayisi: '3+1' },
  },
  {
    ornekKey: 'ornek-emlak-kiralik-ankara',
    baslik: 'Kiralık 1+1 Stüdyo — Çankaya',
    aciklama: 'Kızılay metro yakını, eşyalı, aidat dahil. Öğrenci ve bekar çalışana uygun, hemen taşınır.',
    fiyat: '18500',
    kategori: 'Emlak',
    kategoriId: 'kiralik-daire',
    kategoriKok: 'emlak',
    kategoriYolu: ['emlak', 'konut', 'kiralik', 'kiralik-daire'],
    kategoriEtiket: 'Emlak › Konut › Kiralık › Daire',
    platformlar: ['Sahibinden', 'Emlakjet'],
    konum: { latitude: 39.9208, longitude: 32.8541, il: 'Ankara', ilce: 'Çankaya', etiket: 'Çankaya, Ankara' },
    detay: { emlakTipi: 'Daire', ilanTuru: 'Kiralık', metrekare: '55', odaSayisi: '1+1', esyali: 'Evet' },
  },
  {
    ornekKey: 'ornek-vasita-corolla',
    baslik: '2020 Toyota Corolla 1.6 Vision',
    aciklama:
      'Tramer kaydı yok, yetkili servis bakımlı. İlk sahibinden, boyasız, 62.000 km. Takas değerlendirilir.',
    fiyat: '985000',
    kategori: 'Araç',
    kategoriId: 'otomobil',
    kategoriKok: 'vasita',
    kategoriYolu: ['vasita', 'otomobil'],
    kategoriEtiket: 'Vasıta › Otomobil',
    platformlar: ['Sahibinden', 'Arabam.com'],
    konum: ORNEK_KONUM,
    detay: { aracTipi: 'otomobil', marka: 'Toyota', model: 'Corolla', yil: '2020', kilometre: '62000', yakit: 'Benzin', vites: 'Otomatik' },
  },
  {
    ornekKey: 'ornek-vasita-honda-civic',
    baslik: '2019 Honda Civic 1.6 Eco — Temiz',
    aciklama: 'Boyalı parça yok, 48.000 km, otomatik vites. Yetkili servis bakımlı, takas olur.',
    fiyat: '1125000',
    kategori: 'Araç',
    kategoriId: 'otomobil',
    kategoriKok: 'vasita',
    kategoriYolu: ['vasita', 'otomobil'],
    kategoriEtiket: 'Vasıta › Otomobil',
    platformlar: ['Sahibinden', 'Arabam.com'],
    konum: { ...ORNEK_KONUM, ilce: 'Kartal', etiket: 'Kartal, İstanbul' },
    detay: { marka: 'Honda', model: 'Civic', yil: '2019', kilometre: '48000', yakit: 'Benzin', vites: 'Otomatik' },
  },
  {
    ornekKey: 'ornek-vasita-bmw-320',
    baslik: '2018 BMW 320i M Sport — Premium Galeri',
    aciklama: 'Full M paket, sunroof, deri koltuk. 72.000 km, tramer kaydı yok, kredi kartına taksit.',
    fiyat: '1685000',
    kategori: 'Araç',
    kategoriId: 'otomobil',
    kategoriKok: 'vasita',
    kategoriYolu: ['vasita', 'otomobil'],
    kategoriEtiket: 'Vasıta › Otomobil',
    platformlar: ['Sahibinden', 'Arabam.com'],
    konum: { latitude: 41.0082, longitude: 28.9784, il: 'İstanbul', ilce: 'Şişli', etiket: 'Şişli, İstanbul' },
    detay: { marka: 'BMW', model: '320i', yil: '2018', kilometre: '72000', yakit: 'Benzin', vites: 'Otomatik' },
  },
  {
    ornekKey: 'ornek-vasita-tesla-model3',
    baslik: '2021 Tesla Model 3 Long Range',
    aciklama: '468 km menzil, autopilot, tek şarj istasyonu. 41.000 km, garantili, hızlı teslim.',
    fiyat: '1950000',
    kategori: 'Araç',
    kategoriId: 'otomobil',
    kategoriKok: 'vasita',
    kategoriYolu: ['vasita', 'otomobil'],
    kategoriEtiket: 'Vasıta › Otomobil',
    platformlar: ['Sahibinden'],
    konum: { latitude: 41.0422, longitude: 29.0067, il: 'İstanbul', ilce: 'Beşiktaş', etiket: 'Beşiktaş, İstanbul' },
    detay: { marka: 'Tesla', model: 'Model 3', yil: '2021', kilometre: '41000', yakit: 'Elektrik', vites: 'Otomatik' },
  },
  {
    ornekKey: 'ornek-ikinci-el-iphone',
    baslik: 'iPhone 14 Pro Max 256 GB',
    aciklama: 'Kutusunda, %92 pil sağlığı, Deep Purple. Fatura mevcut, garantisi devam ediyor.',
    fiyat: '42000',
    kategori: 'İkinci El',
    kategoriId: 'cep-telefonu',
    kategoriKok: 'ikinci-el',
    kategoriYolu: ['ikinci-el', 'cep-telefonu'],
    kategoriEtiket: 'İkinci El ve Sıfır Alışveriş › Cep Telefonu',
    platformlar: ['Sahibinden', 'Letgo'],
    konum: ORNEK_KONUM,
    detay: { urunTipi: 'Cep Telefonu', marka: 'Apple', durum: 'İyi' },
  },
  {
    ornekKey: 'ornek-ikinci-el-macbook',
    baslik: 'MacBook Air M2 — Sıfır Ayarında',
    aciklama: '8 GB RAM, 256 GB SSD. Az kullanıldı, çiziksiz. Orijinal şarj aleti ve kılıf hediye.',
    fiyat: '38500',
    kategori: 'İkinci El',
    kategoriId: 'bilgisayar',
    kategoriKok: 'ikinci-el',
    kategoriYolu: ['ikinci-el', 'bilgisayar'],
    kategoriEtiket: 'İkinci El ve Sıfır Alışveriş › Bilgisayar',
    platformlar: ['Sahibinden'],
    konum: ORNEK_KONUM,
    detay: { urunTipi: 'Laptop', marka: 'Apple', durum: 'Sıfır Ayarında' },
  },
  {
    ornekKey: 'ornek-ekskavator-cat',
    baslik: '2018 Caterpillar 320 Ekskavatör',
    aciklama: 'Hidrolik kırıcı dahil, 6.800 saat. Şantiye projesi bitti, hemen teslim. Bakımları eksiksiz.',
    fiyat: '4850000',
    kategori: 'İş Makineleri',
    kategoriId: 'ekskavator-kepce-caterpillar',
    kategoriKok: 'is-makineleri',
    kategoriYolu: ['is-makineleri', 'is-makineleri-grup', 'satilik', 'ekskavator-kepce', 'ekskavator-kepce-caterpillar'],
    kategoriEtiket: 'İş Makineleri › Satılık › Ekskavatör (Kepçe) › Caterpillar',
    platformlar: ['Sahibinden'],
    konum: { latitude: 41.0082, longitude: 28.9784, il: 'İstanbul', ilce: 'Tuzla', etiket: 'Tuzla, İstanbul' },
    detay: { marka: 'Caterpillar', model: '320', yil: '2018', calismaSaati: '6800' },
  },
  {
    ornekKey: 'ornek-beko-jcb',
    baslik: 'JCB 3CX Beko Loder 2017',
    aciklama: 'Kazıcı-yükleyici, 4.200 saat. Paletli lastik, kabin ısıtıcılı. İnşaat ve altyapı işleri için ideal.',
    fiyat: '2150000',
    kategori: 'İş Makineleri',
    kategoriId: 'beko-loder-kazici-yukleyici-jcb',
    kategoriKok: 'is-makineleri',
    kategoriYolu: [
      'is-makineleri',
      'is-makineleri-grup',
      'satilik',
      'beko-loder-kazici-yukleyici',
      'beko-loder-kazici-yukleyici-jcb',
    ],
    kategoriEtiket: 'İş Makineleri › Satılık › Beko Loder › JCB',
    platformlar: ['Sahibinden'],
    konum: { latitude: 38.4237, longitude: 27.1428, il: 'İzmir', ilce: 'Bornova', etiket: 'Bornova, İzmir' },
    detay: { marka: 'JCB', model: '3CX', yil: '2017', calismaSaati: '4200' },
  },
];

export const ORNEK_ILANLAR = ORNEK_ILANLAR_HAM.map((ilan) => ({
  ...ilan,
  oneCikan: ilan.kategoriKok === 'emlak' || ilan.kategoriKok === 'vasita',
  fotograflar: ornekIlanFotograflar(ilan.ornekKey),
}));
